name: CI  # name of the workflow

on:
  push:
    branches: [main]   # push to main branch
  pull_request:
    branches: [main]   # opens a PR to main

jobs:
  test-fastqc-pipeline:
    runs-on: ubuntu-latest   # Linux VM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3   # get code from GitHub

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: envs/fastqc.yaml
          activate-environment: fastqc-env

      - name: Install Snakemake
        run: conda install -c bioconda snakemake

      - name: Run pipeline
        run: snakemake --cores 1   # run Snakefile

      - name: Upload FastQC Report
        uses: actions/upload-artifact@v3
        with:
          name: fastqc-report
          path: results/
