name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-fastqc-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: envs/fastqc.yaml
          activate-environment: fastqc-env

      - name: Run pipeline
        run: snakemake --cores 1

      - name: Upload FastQC Report
        uses: actions/upload-artifact@v4
        with:
          name: fastqc-report
          path: results/
